#!/sbin/runscript

svc_name="AntiVir SAVAPI"

## required binaries
antivir_savapi_bin="/usr/lib/AntiVir/savapi"

## required config files
antivir_savapi_cfg="/etc/antivir-savapi.conf"

opts="${opts} reload"

depend() {
	need net
	use logger dns
}

checkconfig() {
	if [ ! -x "${antivir_savapi_bin}" ]; then
		eerror "SAVAPI binary [${antivir_savapi_bin}] missing"
		return 1
	fi
	if [ ! -r "${antivir_savapi_cfg}" ]; then
		eerror "SAVAPI config [${antivir_savapi_cfg}] missing"
		return 1
	fi
}

start() {
	checkconfig || return 1
	ebegin "Starting ${svc_name}"
	"${antivir_savapi_bin}" --config="${antivir_savapi_cfg}" \
		--allow-remote-shutdown &>/dev/null
	eend $?
}

stop() {
	checkconfig || return 1
	ebegin "Stopping ${svc_name}"
	"${antivir_savapi_bin}" --config="${antivir_savapi_cfg}" \
		--stop &>/dev/null
	eend $?
}

reload() {
	checkconfig || return 1
	ebegin "Reloading ${svc_name}"
	"${antivir_savapi_bin}" --config="${antivir_savapi_cfg}" \
		--reload-engine --allow-remote-shutdown &>/dev/null
	eend $?
}

status() {
	checkconfig || return 1
	ebegin "Checking status of ${svc_name}"
	"${antivir_savapi_bin}" --config="${antivir_savapi_cfg}" \
		--status &>/dev/null
	eend $?
}
